// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.1.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.io.dart' if (dart.library.html) 'bridge_generated.web.dart';

abstract class Savgol {
  Future<Float64List> savgolFilter({required Float64List x, required int windowLength, required int polyOrder, required int derivative, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSavgolFilterConstMeta;
}

class SavgolImpl implements Savgol {
  final SavgolPlatform _platform;
  factory SavgolImpl(ExternalLibrary dylib) => SavgolImpl.raw(SavgolPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory SavgolImpl.wasm(FutureOr<WasmModule> module) => SavgolImpl(module as ExternalLibrary);
  SavgolImpl.raw(this._platform);
  Future<Float64List> savgolFilter({required Float64List x, required int windowLength, required int polyOrder, required int derivative, dynamic hint}) {
    var arg0 = _platform.api2wire_float_64_list(x);
    var arg1 = api2wire_usize(windowLength);
    var arg2 = api2wire_usize(polyOrder);
    var arg3 = api2wire_usize(derivative);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_savgol_filter(port_, arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_float_64_list,
      parseErrorData: _wire2api_String,
      constMeta: kSavgolFilterConstMeta,
      argValues: [
        x,
        windowLength,
        polyOrder,
        derivative
      ],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSavgolFilterConstMeta => const FlutterRustBridgeTaskConstMeta(
        debugName: "savgol_filter",
        argNames: [
          "x",
          "windowLength",
          "polyOrder",
          "derivative"
        ],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  double _wire2api_f64(dynamic raw) {
    return raw as double;
  }

  Float64List _wire2api_float_64_list(dynamic raw) {
    return raw as Float64List;
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
double api2wire_f64(double raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer
